name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
    description: All notable new features and improvements.
  - title: '🎨 Improvements'
    labels:
      - 'improvement'
      - 'enhance'
    description: Performance improvements and optimizations to existing features.
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'speed'
      - 'optimization'
    description: Enhancements that improve the speed and efficiency of the project.
  - title: '♻️ Refactoring'
    labels:
      - 'refactor'
    description: Code refactoring and non-functional changes that don't modify the behavior of the code.
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
      - 'revert'
    description: Fixed bugs and similar improvements.
  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'testing'
    description: Updates to our test suite and quality assurance process.
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
    description: Documentation improvements and typo fixes.
  - title: '🏗️ Build System'
    labels:
      - 'build'
      - 'ci'
      - 'automation'
    description: Changes to our build process and tooling.
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'dependabot'
    description: Routine tasks, repository housekeeping, and other chores.
  - title: '🚧 WIP'
    labels:
      - 'WIP'
    description: Work-in-progress changes that shouldn't be part of the release notes.
  - title: '🗑️ Deprecated & Removed'
    labels:
      - 'deprecated'
      - 'removed'
    description: Features that were removed or deprecated in this release.
  - title: '📈 Version Bumps'
    labels:
      - 'dependencies'
  - title: '💡 Others'
    exclude-labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
      - 'improvement'
      - 'enhance'
      - 'performance'
      - 'speed'
      - 'optimization'
      - 'refactor'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
      - 'revert'
      - 'test'
      - 'testing'
      - 'docs'
      - 'documentation'
      - 'build'
      - 'ci'
      - 'automation'
      - 'chore'
      - 'maintenance'
      - 'dependabot'
      - 'WIP'
      - 'deprecated'
      - 'removed'
      - 'dependencies'
    description: Other miscellaneous changes.
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # What's Changed

  $CHANGES

  For more details see the [full list of changes](https://github.com/kinoplan/utils/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION/).
